package com.timeanddate.services.dataTypes.holidays;

public enum HolidayType {
	ALL, DEFAULT, DEFAULTFORCOUNTRY, OBSERVANCES, FEDERAL, FEDERALLOCAL, LOCAL, FLAGDAYS, LOCALOBSERVANCES, IMPORTANTOBSERVANCES, COMMONOBSERVANCES, OTHEROBSERVANCES, WEEKDAYS, CHRISTIAN, BUDDHISM, HEBREW, HINDUISM, MUSLIM, ORTHODOX, SEASONS, TIMEZONEEVENTS, UNITEDNATIONS, WORLDWIDEOBSERVANCES;
}
